### ISSUE TITLE
Unable to run Bot locally

### ISSUE THREAD

**Issue by msimpsonnz** [Ringobot/ringo#6]
Not sure if it was since the js clean up or app insights, but now unable to run Bot locally, getting the following error
```C:\r\ringo\src\Ringo.Bot\node_modules\applicationinsights\out\AutoCollection\Exceptions.js:33
                        throw error;
                        ^
Error: connect ETIMEDOUT 52.255.52.19:443
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\r\ringo\src\Ringo.Bot\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\r\ringo\src\Ringo.Bot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)```

**Comment by DanielLarsenNZ** [comment]
Who is 52.255.52.19 ? Does not seem to resolve to anything. Is a MSFT IP.

**Comment by msimpsonnz** [comment]
Fixed, combination of user error, wiped out .vscode folder and lauch.json rebuild
